### ISSUE TITLE
Any thoughts about using Builder pattern? 

### ISSUE THREAD

**Issue by Rainer-Lang** [TonnyL/Light#1]

**Comment by TonnyL** [comment]
@Rainer-Lang  Maybe later. At this stage, the answer is negative. If you are willing to do this, you can fork and modify the code by yourself. 😃

**Comment by TonnyL** [comment]
@Rainer-Lang If there is no any other problem, then I will close this issue. If you have any other new idea or advice, do not hesitate to reopen it or just open another one. Happy coding😁!
