### ISSUE TITLE
Remove Kotlin as an implementation detail

### ISSUE THREAD

**Issue by pgreze** [TonnyL/Light#5]
Thank you for this nice library!

I was surprised to find **Companion** references in your README, leaking an implementation detail of your library (= using Kotlin).
But as same time you're using @JvmStatic so you're already generating functions like **Light.success(...)**.

Why not updating the README to avoid using this ugly Companion notation in Java? ;)

**Bonus**: your Light.kt is only including static functions. My advise would be to remove 2 indentation levels by reformating Light.kt like this example:

```kotlin
@file:JvmName("Light")
package io.github.tonnyl.light

fun success(....) { ... }
```
Only bad point: seems not possible to have javadoc for this class :/

**Comment by TonnyL** [comment]
Hi, @pgreze ,

Thanks for your advice. I will update the readme file and remove the ugly code 😂. And I will consider the bonus.
