### ISSUE TITLE
The library Light has max lines allowed?

### ISSUE THREAD

**Issue by dpulgarin** [TonnyL/Light#8]
Hi,

I have imported Light in my project to show, in special cases, long String alerts. The issue appears when the String has 3 lines or more, for example:

"Welcome"
System.lineSeparator()
"Name: Diego Gómez Pérez"
System.lineSeparator()
"You have agreed at 10:00 am"

With these Strings, Light shows:

"Welcome
Name: Diego Gómez ..."

I think that you have a maximum of allowed lines, could you please solve it in some way?

Thanks!

**Comment by TonnyL** [comment]
Hi, @dpulgarin 

The answer is yes. Light is based on [TSnackBar](https://github.com/AndreiD/TSnackBar), and TSnackBar has a maxLines limit of SnackBar text(https://github.com/AndreiD/TSnackBar/blob/master/topsnackbar/src/main/res/layout/tsnackbar_layout_include.xml#L29) and the value is 2 or 1 which is defined in android design library (https://github.com/material-components/material-components-android/blob/8f7dc21a27880eed391f45548a40de8189f31172/lib/java/com/google/android/material/snackbar/res/values/config.xml).

**Comment by dpulgarin** [comment]
Thanks @TonnyL .

Is solved!
